spring:
  application:
    name: RelayBloom
  
  datasource:
    # Production Database (Supabase PostgreSQL)
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
    driverClassName: org.postgresql.Driver
    username: "postgres.kqbriwuqfxnryawqjzuh"
    password: "kubase:rlaskagnsvosalxld"
  
  sql:
    init:
      mode: never # 실제 DB에서는 로컬 테스트용 샘플 데이터를 매번 넣지 않도록 비활성화
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
